#!/bin/bash
#
# Copyright 2015 the Mimu Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
#

#
# Runs a web server on localhost port 8080, serving the app's content.
#

# Figure out the symlink-resolved program name and directory.
cmdName="$(readlink -f "$0")" || exit "$?"
cmdDir="${cmdName%/*}"
cmdName="${cmdName##*/}"
baseDir="${cmdDir%/*}" # Parent of `cmdDir`; often useful.


#
# The main program
#

cd "${cmdDir}"
npx http-server . --port=8080
