#!/bin/bash
#
# Copyright 2015-2025 the Mimu Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0
#

#
# Runs a web server on localhost port 8080, serving the app's content.
#

# Figure out the symlink-resolved program name and directory.
cmdName="$(readlink -f "$0")" || exit "$?"
cmdDir="${cmdName%/*}"
cmdName="${cmdName##*/}"
baseDir="${cmdDir%/*}" # Parent of `cmdDir`; often useful.


#
# The main program
#

npx http-server "${baseDir}" --tls --port=8443 \
    --cert="${cmdDir}/localhost-cert.pem" --key="${cmdDir}/localhost-key.pem"
